sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk7
env:
  global:
    #oss user
  - secure: fu6Ik45CGnGt2bWJSor0yskNWxTP+lm7tkmO9bLvn66z667ji9jAxjYi2p1kOS0PITXfHewWMyaiF6TCoBl5KGbtfpc4wTQH6Xz+Ql4i90X7T7Xn8FsAuFIxXKjYrdWjghtB8kry09NJkKyL7riMoQg7wGIowWI6XBoISRRP/crnydOkGP9oFtSAwFG2IVQTsqAaTXeZGj3S7aBN6NoC7WsPDDRrkIjX0dNULnZKNZsNmlM2mEguIL1bc1lMH+XYsMMKUMu7cFQz4QNv3hB3HMEWWnE/O8yB29vOQYE3ykY8uQXt0XXm+ANRX7uB7SwUDVwgaQMIL8UEZvyNY5GsDDkOFouMqtGy/Nm6gGuFjR8t5wWOXkBmdka9xCD7yGtJT+1vOnlC9jWGDLg/cHwIuEFpUrAser2ubvnhU8g6DBypqwaflA/FRph0LYx0IVO77Jto+VSvvu3pOwUMXOo0+aisuuuoKbzJd4Am8GxmeC10uf+rapSBeWnmsOoE1t4JJipKZOFRyGz5RmaIKAJ0MJznd+6ly8KB+PI8Vq+jqn6YJfMnLE30LzzYehEf10Lsx0+qUyLf7DvCiCIpxrthQybL54wJKpqE9MA3zDulRDHq1QHAkQFkJIuNLCslAbKbkKbWo7mIQh7ZSEHekatAQmAlirH7uJGRhKw0u8CGu5s=
    #oss pass
  - secure: X+DS4PKvYbxrlNdn/G6zNeNKCnYsylocPCyOCqGw8ak6cpLEYjEG4ov3zMUgRA7RrOM+25G7Bgvxcb8d/E8X6safcj/v4XgZwgmRBZhhca6xhuTs6OOolv2figw7je0D+lcLxoWlbZjQ/YXyB7IB5YxgFOE+H5I3hwwovTKBzNM1oDOW2/8EbAJq8nsKN4wkK9dl5KbnVMD4FVgv1k6NYeFzqPckuzoSdP0Js8OTQJ/8ar4/g44/gI45bSj6vUSfLQMIbfga/LWkBKMTLU9HXe2mXQWHHzcPNCgkYafJMX84P67ghuAFaWBzKJr6C3kUH0uOGgLe3AEeQsT75KjA7A4VHcUQXaZI6GDA6SLwm5IAKusiAAljDmlQD5yx67nqqNA0va13yrNOuBfVXGncFpvlPNCQG1RgdmgLZl9lD1Opd/vxs0DfSDSQYZz4q2fwT+BkilztDMqIaCRwQh/0rMuhsaSp+s7u5iYCljeDVY5j66lLBJEKqHkw91atzoM+yjrWV2S+UFNf6uraiNuMVYJeuw51qhA9nArC/YMktMyJYXaIZYFvrHApC2BS399MqBfq/hCaRoxK4DgDvN2XWg+/wBzYB8wndd7g5OEZ5xSbyuU06hW6fN3T3QLlUXbOs6oLE/o1icq/EovZ7VKcsy/IlDAr8NejTb5zzFwTHvg=
    #jenkins user
  - secure: qySkPRFzoVQwPqCUAnciEd++pziYGsF1pDEev+KAbYtyBgGug1ZXvxPQ10q7mvhsHIEzXe2SS0MGEK0HcY+EummGot/qqCrWDhxNreL3tCxmJwjFyL4m9YhMxok/I8aX57EG9lL9BIR9E2nPue755jBq7SkjFpbltGSRAX1coUJab8YAJExdZ/7BgWpLw8PQUBplR2Damb+Flht4Mcqnow7NlMEXvkXP+tD25eYeWeI3leNUOoPbourrBaW2Pkwelkel5GKPzbe+Bnu2yNKPbCXyheb/ncDWfeXIAY00xBm+JVQoHlBGwZaJ7xKpwePvriotEFGoevZWoA5hVKfWLCxIO3VImxwyRtSAtmfPnZU5ge/ZVDJlRizVOcWB6MexjOE/SkuchfVmpxbCBYa1FTJRpn8MnNyAw+IjqUEVjCWR5TZ35ub3HeGcgXCyxa0KWsU8JydSnTdEccuinyi1CqRDJMHcFUDMNUVd1s39LutEWPi0kCGbVDQCJayJ1xZE3uJI2CHoR/A27Jf6Z4Gls3quslq2FCwcUkUbO6efnnIKT4RFeW20fOsGYM+e1mRC+5Ejz0F3DeQ5TuQ/XkthmaLFEPnLnxF3iZXmn/hHW9eyv4xmoaDm7fGykQhDBtQB0w8XHvi278E8E3L+raRAe4URMnm+Y1Iztp69i9erfPk=
    #jenkins pass
  - secure: gwlbo+5R02uUZdKQheYc7SqM3qhxS9pm5l/1RM+fA8XEn/zLXfhjBf4HYZQJgJOc7PQrifLN422E9SqT+HZws2Xkg2zp/Z0cr+iGMLzCLZSpNfJNrQmVpzZW6z9Tmj/OHHnpihNSS5K//0tQVygiqYvNO2s0KszsVaXiZNtPdnP/g+TAXXAVq1Xx/N89gRVylxTRJ3z3XUfcZsTWCaoXZYLHF7oVGwKnLsvD1Is7r/Vp6E4tQSQY+4YAIrUbf5HIX2Ydff8HtG3khXu7kcd71srrwX+e62/ZGhEqlWgZ4kloJYYKvkK4FiloMi0qfAaMRV7PevJGkn0iRE3ShoNk+WZA1naTcf2k9ghn3Z9tlw/AbAGqpZGi4LSlUgaBCA6VZ8DDif3WO/cV2ieH3gQ27KmekIEculpFvylTx2XXZmLEIZ6U+R55xoLYigc+ZCVx/IlYUt075BcL7La9VPJNywArb/ObCYdXb8VPYox45lqgmR52zMVQ1G9fXXzzuKkAU0R3CVCRZwFya7y37WabauFx52anWWCOypsOx0gdSI3j5wvsROV3JxRTdMIWnmn55zoLZiS0lecBrTyikHJERmLnJlPpSiQSKOceeNQqR1dcHiFOKOJ4uVSJsMN56NX21lGLHeqkPTyeloWroGmPPBq1U/Iwfw+qLCEjrHSWpZg=
cache:
  directories:
  - $HOME/.m2
before_install:
- mvn clean -q
install:
- mvn install -Dgpg.skip=true -DskipTests=true -q
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [[ -n "$TRAVIS_TAG" && "$TRAVIS_JDK_VERSION" == "oraclejdk7" ]]; then openssl
  aes-256-cbc -K $encrypted_a87434bbd25b_key -iv $encrypted_a87434bbd25b_iv -in cd/codesigning.asc.enc
  -out cd/codesigning.asc -d; gpg --fast-import cd/codesigning.asc; mvn clean install
  deploy --settings .settings.xml; fi
notifications:
  email:
    recipients:
    - bogdan.livadariu@gmail.com
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/e93317838b869a9d5014
    on_success: change
    on_failure: always
    on_start: never
